let error = std.error("something bad happened", nil)
error.context = "oops..."
